### ISSUE TITLE
windows not find filename 

### ISSUE THREAD

**Issue by catafest** [MrValdez/arwing#1]
my python 2.7 is ok with path under enviroment 
I got this error:

`C:\Python27>python.exe arwing-master\main.py
Traceback (most recent call last):
  File "arwing-master\main.py", line 280, in <module>
    main()
  File "arwing-master\main.py", line 243, in main
    model = create_model_list(modelname)
  File "arwing-master\main.py", line 150, in create_model_list
    vertices, texture_vertices, groups = load_model(modelname)
  File "arwing-master\main.py", line 74, in load_model
    with open(modelname) as f:
IOError: [Errno 2] No such file or directory: 'model/arwing.obj'`

**Comment by catafest** [comment]
Fix it. You need to update your code or can be used with 

```
C:\Python27\arwing-master>python main.py
```

I check error with

```
import os
print os.path.abspath('model/arwing.obj')
C:\Python27\arwing-master\model\arwing.obj
```
